"""
Django settings for storeBackEnd project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config  # For environment variable management

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-)&tm8&tbv334)_q+44m#znc*yf^p1vt13o%nbti68a5!6xiol+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.1.192", "*.liara.run", "your-liara-app-name.liara.run"]

SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000/')

MEDIA_URL = "storeBackEnd/digitalAssets/frontEnd/images/"
MEDIA_ROOT = os.path.join(BASE_DIR, "storeBackEnd/digitalAssets/frontEnd/images")

APPEND_SLASH = False

# Application definition
JAZZMIN_UI_TWEAKS = {
    "dark_mode_theme": "darkly"
}

JAZZMIN_SETTINGS = {
    "theme": "simplex",
}

INSTALLED_APPS = [
    "corsheaders",
    "ckeditor",
    "colorfield",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "jazzmin",
    "django.contrib.admin",
    "frontEnd.apps.FrontendConfig",
    "websiteInfo.apps.WebsiteinfoConfig",
    "reactui.apps.ReactuiConfig",
    "API.sendEmail",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

SITE_ID = 1

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://your-liara-app-name.liara.run",  # Add your production frontend URL
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

ROOT_URLCONF = "storeBackEnd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "reactui/build"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "storeBackEnd.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# other codes ...
import os
DATABASES = {
    'default': {
        'ENGINE':   'dj_db_conn_pool.backends.mysql', 
        'NAME':     os.getenv("tender_mccarthy"), 
        'USER':     os.getenv("root"),
        'PASSWORD': os.getenv("USAY07loBRNIpnh3GlV2hX3R"),
        'HOST':     os.getenv("my1"),
        'PORT':     os.getenv("3306"),
    },
}
# other codes ...
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [  # Removed leading space to fix indentation
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "reactui/build/static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

WEBPACK_LOADER = {
    "DEFAULT": {
        "BUNDLE_DIR_NAME": "bundles/",
        "STATS_FILE": os.path.join(BASE_DIR, "reactui", "build", "webpack-stats.json"),
    }
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('MAIL_HOST', default='smtp.c1.liara.email')
EMAIL_PORT = config('MAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('MAIL_USER', default='nifty_kowalevski_cli22r')
EMAIL_HOST_PASSWORD = config('MAIL_PASSWORD', default='49f5a29c-f437-41d5-9418-b256760fed2e')
EMAIL_USE_TLS = False  # Disable STARTTLS
EMAIL_USE_SSL = True  # Force TLS
MAIL_FROM = f"{config('MAIL_FROM_NAME', default='Anjoman')} <{config('MAIL_FROM_ADDRESS', default='anjoman@alucarddev.ir')}>"

BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')